title: "Site da disciplina Matemática Elementar"
description: "IMD1001 - Matemática Elementar | Instituto Metrópole Digital (IMD) | Universidade Federal do Rio Grande do Norte (UFRN)"
theme: jekyll-theme-cayman